### ISSUE TITLE
CSS Variable Images

### ISSUE THREAD

**Issue by rctneil** [rails/propshaft#185]
I ahve some images being referenced to from my HTML:

`<html style="--colour: <%= COLOUR %>; --colour-texture: url('canvas-<%= COLOUR %>.png');">`

When referencing those variables in my CSS:

`background: transparent var(--colour-texture) repeat center center;`

it fails. If I put the computed variable definition into the CSS, it works fine.   I assume i need to manually tell propshaft about those images ahead of time.  

Where, and how can I do this?

**Comment by theodorton** [comment]
My recommendation would be to move those variable definitions to your CSS file. Something like this:

```css
// This would be the default
html {
  --colour: red;
  --colour-texture: url('canvas-red.png');
}

html.theme--blue {
  --colour: blue;
  --colour-texture: url('canvas-blue.png');
}
```

As that would give Propshaft the opportunity to replace the paths passed to the URLs with the digested versions.

Another alternative would be to store your `canvas-#{COLOUR}.png` files directly in the `public/` folder - this way they are not digested.

There might be some method available in Propshaft to give you the digested asset name, but the idea of calling that on every page load seems very inefficient compared to the alternatives above. Assuming you have few `canvas-*.png` files - they seem more explicit and simpler to maintain.

What do you use to generate your CSS? If you haven't renamed the entrypoint in `app/assets/stylesheets` the file extension should be `.postcss.css`, `.tailwind.css` or something similar.
