### ISSUE TITLE
Importing libraries with fonts from node_modules (Bootstrap Icons example)

### ISSUE THREAD

**Issue by SebouChu** [rails/propshaft#47]
Hello!

I created a sample Rails 7 RC1 application with Propshaft and I wanted to use [Bootstrap Icons](https://icons.getbootstrap.com/) from NPM package.

As you can see in the README of [my sample app](https://github.com/SebouChu/propshaft-sample-app), I had to play a few tricks to make them work because the fonts import didn't work out-of-the-box.

I wanted some advice from multiple developers if there was a potential issue with Propshaft not handling the default font path correctly in [`bootstrap-icons`](https://github.com/twbs/icons/blob/b69fe3911e064d1baa772393aa96bb082f420872/font/bootstrap-icons.scss#L2) and if there's not, if my workaround is good. I tried a few things and I don't know if it is the smartest solution.

This discussion may lead to write some documentation for best practices around Propshaft.

Thanks in advance for your help!

**Comment by brenogazzola** [comment]
Adding the node_modules folder like you did is correct. Propshaft adds some base folders but expects you to add other folders you need, like Sprockets did. 

The second change, removing the fingerprint after “?” however is something we can try to improve. I’m not very familiar with bootstrap, so are you sure that just removing that part of the url is enough?

**Comment by SebouChu** [comment]
Looks like it. When I run `rails assets:precompile`:
- It adds the font files in the `public/assets` folder
- It adds the two entries in the `public/assets/.manifest.json`
  ```json
  {
    "fonts/bootstrap-icons.woff2": "fonts/bootstrap-icons-00150349e6ebdaf2628af9ea4e56d6b02dbda393.woff2",
    "fonts/bootstrap-icons.woff": "fonts/bootstrap-icons-d644d61b4bc7925875ad953cc381b4a722b334d2.woff"
  }
  ```

Unfortunately, the fingerprint prevents the `url()` mapping in the compiled `application-[digest].css`. Below, the results of `rails assets:precompile`:

- Without the fingerprint (OK)

```scss
@font-face {
  font-family: "bootstrap-icons";
  src: url("/assets/fonts/bootstrap-icons-00150349e6ebdaf2628af9ea4e56d6b02dbda393.woff2") format("woff2"), url("/assets/fonts/bootstrap-icons-d644d61b4bc7925875ad953cc381b4a722b334d2.woff") format("woff");
}
```

- With the fingerprint (KO)

```scss
@font-face {
  font-family: "bootstrap-icons";
  src: url("./fonts/bootstrap-icons.woff2?30af91bf14e37666a085fb8a161ff36d") format("woff2"), url("./fonts/bootstrap-icons.woff?30af91bf14e37666a085fb8a161ff36d") format("woff");
}
```
